### ISSUE TITLE
Resetting password bug

### ISSUE THREAD

**Issue by jayaregalinada** [basco-johnkevin/laravelsnippets#102]
27th of June 2014, I joined and finally activate the account from the link provided by the email notification entitled "Activate your account!"

However, June 28, 2014 6:26 AM GMT+8 I tried to test how the password reset works, and surprisingly an email notification with a link for password reset. `http://laravelsnippets.com/password/reset/{password_reset_identification}`. But as I clicked the link provided the headers status code is a 404 Not Found.

**Comment by ionut-tanasa** [comment]
Fixed #105
